# Generated by Django 5.1.3 on 2024-11-26 21:42

import django.core.validators
import django.db.models.deletion
import juxi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('date_reference', models.DateTimeField(default=juxi.models.default_time)),
                ('time_unit', models.CharField(choices=[('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('hour', 'Hour'), ('minute', 'Minute')], default=('day', 'Day'), max_length=8)),
                ('every_nth', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_template', models.TextField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juxi.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('code', models.TextField()),
                ('output', models.TextField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juxi.taskseries')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
    ]
