# Generated by Django 5.1.3 on 2024-11-30 11:11

import django.core.validators
import django.db.models.deletion
import juxi.models.schedule
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('date_reference', models.DateTimeField(default=juxi.models.schedule.default_time)),
                ('time_unit', models.CharField(choices=[('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('hour', 'Hour'), ('minute', 'Minute')], default='day', max_length=8)),
                ('every_nth', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code_template', models.TextField(default="#!/usr/bin/env -S bash -eEu -o pipefail\n\necho 'TODO'")),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juxi.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('code', models.TextField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=-1)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juxi.taskseries')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
    ]
