# Generated by Django 5.1.3 on 2024-11-26 22:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='output',
            field=models.TextField(blank=True),
        ),
    ]

#TODO @mark: squash

