# Generated by Django 5.1.3 on 2024-12-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
