# Generated by Django 5.1.3 on 2024-11-28 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juxi', '0002_taskrun_end_at_alter_taskrun_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='status',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
